---
title: "R Notebook"
output: html_notebook
---
```{r libraries}
library(readr)
library(ggplot2)
#library(plotly)
```

Next Steps:

-ungroup Cavs

-Group date as month

-Box plot:
	rebounds 
	assists
	TO
	any box score stat

```{r get_data, message= FALSE}
urlfile <- "https://raw.githubusercontent.com/dreslow/Lebron_Learning/master/LebronProject/LebronAllStats.csv"
  
data <- read_csv(url(urlfile))

```

```{r subset}
drop1 <- c('FG',"FGA","FG%","3P","3PA","3P%","FT","FTA","FT%","GmSc","PlusMinus", "PTS", "10PT BCKT")

data_names <- data[,!names(data) %in% drop1]

cols <- colnames(data_names)
```

```{r message = FALSE}

plot_list = list()
for (feature in cols) {
  
    p <- ggplot(data = data, mapping = aes(x = .data[[feature]], y = data$"PTS"))
    p <- p + geom_point()
    p <- p + xlab(feature) +ylab('Continuous. Points')
    
    plot_list[[feature]] <- p
}

pdf("dotplots.pdf")
for (feature in cols) {
    print(plot_list[[feature]])
}
dev.off()

```


```{r buckets message = FALSE}

plot_list = list()
for (feature in cols) {
  
    p <- ggplot(data = data, mapping = aes(x = .data[[feature]], y = data$"10PT BCKT"))
    p <- p + geom_point()
    p <- p + xlab(feature) +ylab('Bucketed Points')
    
    plot_list[[feature]] <- p
}

pdf("bucketplots.pdf")
for (feature in cols) {
    print(plot_list[[feature]])
}
dev.off()

```