---
title: "R Notebook"
output: html_notebook
---
```{r libraries, message =FALSE}
library(readr)
library(ggplot2)
library(tidyverse)
#library(plotly)
```

Next Steps:

-Box plot:
	rebounds 
	assists
	TO
	any box score stat

```{r get_data, message= FALSE}
urlfile <- "https://raw.githubusercontent.com/dreslow/Lebron_Learning/master/LebronProject/LebronAllStats.csv"
  
data <- read_csv(url(urlfile))

```

```{r ungroup_cavs}
# 32 -> 8 -> 32 -> 22
#sort to Cavs1 -> Heat -> Cavs2 -> Lakers
# 0, 887, 1215

data <- data %>%
  mutate(Team.name = if_else(`Team` == 8,'Heat',
                        if_else(`Team` == 22, 'Lakers',
                        if_else((`Team` == 32 & `Season` < 11), 'Cavs1', 'Cavs2'))))
```

```{r subset}
drop1 <- c('FG',"FGA","FG%","3P","3PA","3P%","FT","FTA","FT%","GmSc","PlusMinus", "PTS", "10PT BCKT", "Team")

data_names <- data[,!names(data) %in% drop1]

cols <- colnames(data_names)
```


```{r message = FALSE}

plot_list = list()
for (feature in cols) {
  
    p <- ggplot(data = data, mapping = aes(x = .data[[feature]], y = data$"PTS", color = `Home(0)/Away(1)`))
    p <- p + geom_jitter()
    p <- p + xlab(feature) +ylab('Continuous. Points')
    
    plot_list[[feature]] <- p
}

pdf("dotplots.pdf")
for (feature in cols) {
    print(plot_list[[feature]])
}
dev.off()

```


```{r buckets message = FALSE}

plot_list = list()
for (feature in cols) {
  
    p <- ggplot(data = data, mapping = aes(x = .data[[feature]], y = data$"10PT BCKT"))
    p <- p + geom_point()
    p <- p + xlab(feature) +ylab('Bucketed Points')
    
    plot_list[[feature]] <- p
}

pdf("bucketplots.pdf")
for (feature in cols) {
    print(plot_list[[feature]])
}
dev.off()

```

```{r hist message = FALSE}

plot_list = list()
for (feature in cols) {
  
    p <- ggplot(data = data, mapping = aes(x = .data[[feature]]))
    p <- p + geom_histogram()
    p <- p + xlab(feature) +ylab('Count') + theme_classic()
    
    plot_list[[feature]] <- p
}

pdf("hists.pdf")
for (feature in cols) {
    print(plot_list[[feature]])
}
dev.off()

```

